
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: .
      dockerfile: ./microservice-eureka/Dockerfile
    image: eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    
  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: ./microservice-order/Dockerfile
    image: order-service:latest
    ports:
      - "8090:8090"
    networks:
      - microservices-network
    depends_on:
      - eureka-server
  
  inventory-service:
    container_name: inventory-service
    build:
      context: .
      dockerfile: ./microservice-inventory/Dockerfile
    image: inventory-service:latest
    ports: 
      - "9090:9090"
    networks:
      - microservices-network
    depends_on:
      - eureka-server
  
  tracking-service:
    container_name: tracking-service
    build:
      context: .
      dockerfile: ./microservice-tracking/Dockerfile
    image: tracking-service:latest
    ports:
      - "8091:8091"
    networks:
      - microservices-network
    depends_on:
      - eureka-server
  
  order-db:
    container_name: order_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    volumes:
      - orderdb-data:/var/lib/postgresql/data

  inventory-db:
    container_name: inventory_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventorydb
    ports:
      - "3306:3306"
    networks:
      - microservices-network
    volumes:
      - inventorydb-data:/var/lib/mysql
  
  traking-db:
    container_name: tracking_db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - microservices-network
    volumes:
      - trackingdb-data:/data/db

# Redes de los microservicios
networks:
  microservices-network:
    driver: bridge

# Vol√∫menes para persistencia de datos
volumes:
  orderdb-data:
  inventorydb-data:
  trackingdb-data: